### ISSUE TITLE
[potential bug] unexpected result in dimer analysis

### ISSUE THREAD

**Issue by ganschow** [quwubin/MFEprimer-3.0#11]
Given two primer sequences P1 and P2 with largely complementary 3' ends, I would expect that dimers are formed by overlapping 3' ends. However, `mfeprimer dimer` (v3.2.0) also predicts a dimer species where the 3' end of P1 overlaps the non-complementary 5' end of P2 (see 'Dimer 2' and 'Dimer 3' in log file). Why is this?

[test.log](https://github.com/quwubin/MFEprimer-3.0/files/7286169/test.log)

**Comment by quwubin** [comment]
This bug has been fixed, thanks, please test the new version here: https://github.com/quwubin/MFEprimer-3.0/releases/tag/v3.2.4
