### ISSUE TITLE
[Enhancement] Define amount of cores to use

### ISSUE THREAD

**Issue by RoySimons96** [quwubin/MFEprimer-3.0#12]
Hello,

Would it be possible to add a flag to define the amount of cores that will be used by MFEprimer?
MFEprimer is now using all cores by default, which is inconvenient when working in shared environments.

Thanks.

**Comment by quwubin** [comment]
Hi,

Thanks. 

MFEprimer has a flag `--cpu 4` for cpu cores. However, for my test, it still used shared cores though the total percent is right.

Below is my test commands, I use 4 and 6 cores for testing:
```
mfeprimer -d ~/db/hg19_chrM16569/hg19_chrM16569.fa -i amp-T1-primer.fa -S 500 -o amp-T1-primer.fa.mfe -c 4
mfeprimer -d ~/db/hg19_chrM16569/hg19_chrM16569.fa -i amp-T2-primer.fa -S 500 -o amp-T2-primer.fa.mfe -c 6
```

<img width="1392" alt="截屏2022-02-05 下午7 08 40" src="https://user-images.githubusercontent.com/9742/152639751-251891bb-53e6-45f3-945d-56a044bda930.png">


[mfeprimer-3.2.5-windows-4.0-amd64.exe.gz](https://github.com/quwubin/MFEprimer-3.0/files/8007878/mfeprimer-3.2.5-windows-4.0-amd64.exe.gz)
[mfeprimer-3.2.5-linux-amd64.gz](https://github.com/quwubin/MFEprimer-3.0/files/8007879/mfeprimer-3.2.5-linux-amd64.gz)
[mfeprimer-3.2.5-darwin-10.6-amd64.gz](https://github.com/quwubin/MFEprimer-3.0/files/8007880/mfeprimer-3.2.5-darwin-10.6-amd64.gz)

I will keep looking for a solution to this question.

**Comment by quwubin** [comment]
Hi, 

I think I found the solution. Please download here: https://github.com/quwubin/MFEprimer-3.0/releases/tag/v3.2.5

<img width="1392" alt="截屏2022-02-21 下午2 02 21" src="https://user-images.githubusercontent.com/9742/154898097-c0b15be2-3f68-416f-b9a4-11c941e9902c.png">

**Comment by RoySimons96** [comment]
Thank you for the implementation.
Could this flag be added to the separate commands:
mfeprimer hairpin
mfeprimer dimer 
?

**Comment by quwubin** [comment]
> 

added and please test the latest version: https://github.com/quwubin/MFEprimer-3.0/releases/tag/v3.2.6

**Comment by RoySimons96** [comment]
Hi quwubin, 

It seems the -c flag is not present in either the dimer and hairpin subcommands.

![image](https://user-images.githubusercontent.com/36704719/167827668-337e83af-f12d-4e86-8c41-3ca749cad5b7.png)

**Comment by quwubin** [comment]
I updated the files, and sorry for the wrong files.
