### ISSUE TITLE
Indexing exceeds memory percent to use (MFEprimer 3.2.4)

### ISSUE THREAD

**Issue by ghost** [quwubin/MFEprimer-3.0#13]
When I execute `mfeprimer index -h`, one of the flags tell me:

`-m, --memory float memory percent to use, e.g. 70 for 70% (default 70)`

But when I index my genomes (~70,000 SARS-CoV-2 genomes), my memory usage exceeds 70%. The command I used was:

`mfeprimer index -i sc2.fasta`

![over_70](https://user-images.githubusercontent.com/46197634/155699933-a25feb40-1a5f-4672-8f43-3f843fa53d9a.PNG)

Image shows 59.7gb being used out of 62.5gb (95.5% of memory usage).

**Comment by quwubin** [comment]
The quick solution is set `-s 1000000` and `-m 50` for a small value.

I will continue to find a better solution.

**Comment by quwubin** [comment]
A better solution is spliting into several smaller database. And use `mfeprimer -d db1.fa -d db2.fa` for multiple database check.
