### ISSUE TITLE
Addition of output in tabular form (e.g. tsv) for specificity analysis

### ISSUE THREAD

**Issue by linxianzu1995** [quwubin/MFEprimer-3.0#17]
Hi, I have 72 primers and I use mfeprimer for primer specific analysis. The output file size in json format is quite large (5.2 GB json.gz) and it is very inconvenient to use Python for further analysis, mainly because of the lack of memory due to the large file size.

**Comment by quwubin** [comment]
Thanks, I will add to my todo list.

**Comment by quwubin** [comment]
Hi,

Please download here: https://github.com/quwubin/MFEprimer-3.0/releases/tag/v3.3.0
