### ISSUE TITLE
Command-line version of MFEprimer enables primer design

### ISSUE THREAD

**Issue by Reynababy** [quwubin/MFEprimer-3.0#18]
Hello, it is very nice to be able to use MFEprimer to verify the dimerization, hairpin structure and specificity of the primer sequences。I found that the web version of MFEprimer can implement primer design, but the command-line did not find the function to implement primer design.

**Comment by quwubin** [comment]
The MFEprimer is designed as a general tool for primer quality control. 
For primer design for different applications, I have plan to release more useful web server in future. 

Thanks for your comments.
