### ISSUE TITLE
Batch runs produce a small number of empty results

### ISSUE THREAD

**Issue by gewenlong365** [quwubin/MFEprimer-3.0#19]
Software version：MFEprimer-3.2.7

When a batch job is executed, some results will be empty, and when run separately, some results will be returned
```bash
mfeprimer -i 03_true_primer/primer0.fa -d pos_index/positive.fa -o out_03_true_primer/primer0.fa.out -c 10
mfeprimer -i 03_true_primer/primer1.fa -d pos_index/positive.fa -o out_03_true_primer/primer1.fa.out -c 10
mfeprimer -i 03_true_primer/primer10.fa -d pos_index/positive.fa -o out_03_true_primer/primer10.fa.out -c 10
mfeprimer -i 03_true_primer/primer100.fa -d pos_index/positive.fa -o out_03_true_primer/primer100.fa.out -c 10
mfeprimer -i 03_true_primer/primer1000.fa -d pos_index/positive.fa -o out_03_true_primer/primer1000.fa.out -c 10
mfeprimer -i 03_true_primer/primer1001.fa -d pos_index/positive.fa -o out_03_true_primer/primer1001.fa.out -c 10
...
```
The number of commands exceeds 1000
对比如下
![image](https://github.com/quwubin/MFEprimer-3.0/assets/78864083/ef161eac-154d-4800-bcfb-8222d26711a8)
![image](https://github.com/quwubin/MFEprimer-3.0/assets/78864083/971090af-8dc5-4ab2-b2a1-54468a9438c6)

**Comment by quwubin** [comment]
初步判断是同时打开的文件太多，同时进行的分析命令控制在 1000 或者 100 以下，应该不会出现这个问题。
有问题再反馈，感谢。
