### ISSUE TITLE
Can you also release a version complied on apple Arms CPU M1/M2?

### ISSUE THREAD

**Issue by scleraxis** [quwubin/MFEprimer-3.0#20]
Looks like the Darwin amd64 version is not compatible with Apple latest models. Not that urgent, but it will be very helpful, maybe in next update?

**Comment by quwubin** [comment]
Hi,

Please download here: https://github.com/quwubin/MFEprimer-3.0/releases/tag/v3.3.0

**Comment by scleraxis** [comment]
Thank you, it works on my Mac.
