### ISSUE TITLE
Error occurred while I running mfeprimer on Linux

### ISSUE THREAD

**Issue by Zhengfy1022** [quwubin/MFEprimer-3.0#23]
I run mfeprimer 3.2.2 with a fasta file which has 5000s sequences, but it encountered an error while running, below is the detailed information of the error: 
panic: runtime error: slice bounds out of range [:-3]

goroutine 95860623 [running]:
github.com/quwubin/bio/mfeprimer.matchPair(0xc000136120, 0x2a, 0xc00023d860, 0xc000276b40, 0xc06957f9a0, 0x4, 0x4, 0xc096ccf128, 0x3, 0x3, ...)
        /Users/quwb/quwubin/bio/mfeprimer/mfeprimer.go:1167 +0x1ab2
github.com/quwubin/bio/mfeprimer.searchPairedAmpliconsParallel.func2(0xc001eb41e8, 0x0)
        /Users/quwb/quwubin/bio/mfeprimer/mfeprimer.go:980 +0x290
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc089fd2210, 0xc692af33e0)
        /Users/quwb/gocode/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /Users/quwb/gocode/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:54 +0x66

while I see the log, the program stop running when testing AGACGATGCTGCTGCT vs. AGTCGATCATCGGGATTCAGCAGCAG
Then I tried running this two sequences using different versions of mfeprimer, but it not works. How can i get the right way to deal with this problem?
Thank you so much.

**Comment by quwubin** [comment]
Hi,

I also need the database to find the error, thanks.

**Comment by Zhengfy1022** [comment]
The database and primer file have been provided in the attachment, DX300.part4 is the database and 2_19_100 is the primer file.&nbsp;
Here is the commend:
${Bin}/mfeprimer-3.2.2-linux-amd64 spec -i 2_19_100.fasta -o 2_19_100.mfe.txt -d DX300.part_004.fasta


Thank you so much.




郑福元
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "quwubin/MFEprimer-3.0"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月19日(星期二) 上午10:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [quwubin/MFEprimer-3.0] Error occurred while I running mfeprimer on Linux (Issue #23)





 
Hi,
 
I also need the database to find the error, thanks.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

DX300.part_004.fasta (1.20G, 2024年04月18日 11:06 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=79316635bdbab3d026e7967f1f37034c48450556580304551d505e06011a000508014b535f0f084e565455050c03035356050701392331276802560517475011446e56050d1957024345073504&code=01f5971c

**Comment by quwubin** [comment]
Bug fixed, please test the latest version: https://github.com/quwubin/MFEprimer-3.0/releases/tag/v3.3.1

Thanks.
