### ISSUE TITLE
Primer delta option 

### ISSUE THREAD

**Issue by BR-bhumm** [quwubin/MFEprimer-3.0#24]
Is there any way to set a maximum delta or range between forward and reverse primers for predicted amplicons when using the `mfeprimer spec` command? Or is it possible to ad this feature in future releases?

As an example, I set my `-t` flag to 45C. Some of my predicted amplicons have very divergent Tms (FpTm - 64C, RpTm - 48C). The ability to filter predicted amplicons based on Tm range (i.e., ± 5C) would be very beneficial.

**Comment by quwubin** [comment]
OK, I just don't know why we need to filter out a stable binding?

**Comment by quwubin** [comment]
Added, please test the latest version.
