### ISSUE TITLE
fatal error: out of memory, Create index required too much memory!

### ISSUE THREAD

**Issue by kmosi0** [quwubin/MFEprimer-3.0#25]
An error occurred in a allocated memory， while I use a rice genome（400Mb file size） to create index with 50Gb memory. Is the memory to low for creating index ? if is, it need to much memory. Wish for you help! here is the error info blow. 
`created by github.com/quwubin/mfeprimer/cmd.makeIndex in goroutine 1
        /Users/quwb/gocode/src/github.com/quwubin/mfeprimer/cmd/index.go:292 +0x4e0
runtime: out of memory: cannot allocate 4194304-byte block (3916169216 in use)
fatal error: out of memory
goroutine 35 [running]:
runtime.throw({0x8317425, 0xd})
        /Users/quwb/local/go/src/runtime/panic.go:1077 +0x4d fp=0x9ed1d08 sp=0x9ed1cf4 pc=0x8083dcd
runtime.(*mcache).refill(0x555afca8, 0x5)`

**Comment by quwubin** [comment]
Hi,

Please adjust following parameters:
```
-m 50
-s 1000000
```

**Comment by kmosi0** [comment]
I have tried the parameters such as lower memory and block size, it seems didn't work even  run in 200 GB RAM HPC. Hundreds of primerqc.tmp files had been generated, but did not merge to one. It seems the IRGSP1.0 genome in you 4.0 version web server can't work too.
`# LSBATCH: User input
./mfeprimer-3.3.0-linux-386  index  -c 8 -m 20 -s 500000 -i IRGSP-1.0_genome.fasta
------------------------------------------------------------

Exited with exit code 2.

Resource usage summary:

    CPU time :                                   7139.39 sec.
    Max Memory :                                 2823 MB
    Average Memory :                             604.04 MB
    Total Requested Memory :                     10000.00 MB
    Delta Memory :                               7177.00 MB
    Max Swap :                                   -
    Max Processes :                              3
    Max Threads :                                14
    Run time :                                   5864 sec.
    Turnaround time :                            5867 sec.
runtime: out of memory: cannot allocate 41943040-byte block (2964422656 in use)
fatal error: out of memory

goroutine 1 [running]:`

**Comment by kmosi0** [comment]
![图片](https://github.com/quwubin/MFEprimer-3.0/assets/44768134/5f877a56-dec3-44f1-925a-f7635fcc0e91)  TGCTCGGATTCTCCATCCAC 
GGTGAGTCGCTGTTGAGACA this primer could match well in ncbi ,but can not get the mathch in you web server for rice genome version 7, get error in IRGSP 1.0 genome.

**Comment by quwubin** [comment]
## IRGSP-1.0 for MFEprimer is availabe now

Here is the result https://m4.igenetech.com/spec/2b1a830f-ed3c-4dcd-ac49-260e0b67ecd0

## Index problem

The algorithm requires a large memory to store index before writing to disk, `-m` is for what percent of memory will be used for indexing. Please try 50 or 60, otherwise, the algorithm will have to dump many temperoty files into disk.

**Comment by kmosi0** [comment]
> ## IRGSP-1.0 for MFEprimer is availabe now
> 
> Here is the result https://m4.igenetech.com/spec/2b1a830f-ed3c-4dcd-ac49-260e0b67ecd0
> ## Index problem
> 
> The algorithm requires a large memory to store index before writing to disk, `-m` is for what percent of memory will be used for indexing. Please try 50 or 60, otherwise, the algorithm will have to dump many temperoty files into disk.

Thanks, IRGSP-1.0 genome on website server is working finely now. but the local index remain failure with the parameter -m 50, using100GB RAM in HPC, neither using the -s 1000000 or not. if using the -s 1000000, no error message, and the split .primerqc.tmp file is generated too, but can't merge to one file finally.

**Comment by quwubin** [comment]
I believe that's due to your use of 32-bit software.
Anyway, I've copied the index to a temporary server (http://23.239.1.79:8200/); please download it to your local machine.
Please tell me when you download them all.

**Comment by kmosi0** [comment]
> I believe that's due to your use of 32-bit software. Anyway, I've copied the index to a temporary server (http://23.239.1.79:8200/); please download it to your local machine. Please tell me when you download them all.

you are right, I used the wrong version, it work now. Thank you!
