### ISSUE TITLE
Tm filter

### ISSUE THREAD

**Issue by rwtaylor** [quwubin/MFEprimer-3.0#5]
Hi, the Tm filter seems to only filter amplicons. It would be great to have it also filter bindings, dimers, and hairpins. Would that be difficult to add? Maybe different flags? Is there is a reason that it doesn't?

Thanks!

**Comment by quwubin** [comment]
Tm filter is for primer binding, any bindings have Tm lower than the Tm cutoff will not be displayed. [This page](https://mfeprimer3.igenetech.com/spec/7c3c1c9e-964d-45cc-a715-3d5a3f82d627) is for Tm = 30. So, amplicons with lower primer bindings will not be displayed. 

Dimers and hairpins have cutoff values to filter them, for example, the Tm, delta G and the score. 

`➜  ~ mfeprimer dimer
Error: required flag(s) "in" not set
Usage:
  mfeprimer dimer [flags]

Flags:
  -i, --in string      [*] a file contains primer sequences in fasta format
  -o, --out string     output file name, e.g., dimer.txt
  -t, --tm float       tm cutoff value to filter the dimers
  -d, --dg float       delta G cutoff value to filter the dimers
  -s, --score int      score cutoff to trigger a dimer (default 5)
  -m, --mismatch int   allowed max mismatches for a dimer (default 2)
  -p, --primer         only output dimers with 3'end binded
      --mono float     concentration of monovalent cations [mM] (default 50)
      --diva float     concentration of divalent cations [mM] (default 1.5)
      --dntp float     concentration of dNTPs [mM] (default 0.25)
      --oligo float    concentration of annealing oligos [nM] (default 50)
  -h, --help           help for dimer

required flag(s) "in" not set
`
