### ISSUE TITLE
how does k-mer size affect the results

### ISSUE THREAD

**Issue by biozzq** [quwubin/MFEprimer-3.0#6]
Dear all,

I want to generate the 120 nt probe sequences on my own genomes. I also have a look at the `OligoMiner` tool (https://github.com/beliveau-lab/OligoMiner) .  I will chose `MFEprimer` in my study. However, some questions confused me about it, such as how to set the k-mer size, when I set the k-mer size to 18, the program (mfeprimer-3.2.1-linux-amd64 index -k 18 -i reference.fa) always run out of memory. Some other parameters about the probe sequences quality control, such as tm cutoff in `mfeprimer-3.2.1-linux-amd64 dimer`. In my experiment, the probes will be added and hybridised to the prepared library at 65°C (If the tm of the structure is lower than my reaction conditions, then this structure will not cause any problems). I was wonder that if I should set the tm to 65 when running `mfeprimer-3.2.1-linux-amd64 dimer`. Also, about the delta G parameters in `mfeprimer-3.2.1-linux-amd64 hairpin`, I know that more negative of delta G will be problematic. Hope you can give me some suggestions. Thank you very much.

Best wishes,
Zheng zhuqing

**Comment by quwubin** [comment]
MFEprimer is designed for short primers, usually in 15-40 nt.

Probes with 120 nt in size should use other ways to check the specificity, the strategy of MFEprimer is not suitable for probe hybridization application.

For dimers and hairpins, the score value should work. But the delta G and Tm is not accurate anymore.

**Comment by biozzq** [comment]
Hi @quwubin 

Thanks for your information. If the score values work, how to interpret them, do the small ones imply high quality? More, do you have any suggestions about generating the long hybridization probes, such as the widely used software? Thank you very much.

Best,
Zheng zhuqing

**Comment by biozzq** [comment]
Hi @quwubin 

I will not use MFEprimer to test the specificity. I just want to test the dimer and hairpin in my probe library, if the scores work, it will be very appreciated.

Zheng zhuqing

**Comment by quwubin** [comment]
> Hi @quwubin
> 
> I will not use MFEprimer to test the specificity. I just want to test the dimer and hairpin in my probe library, if the scores work, it will be very appreciated.
> 
> Zheng zhuqing

Then you don't need to index the database, just run `mfeprimer dimer -i probe.fa` or `mfeprimer hairpin -i probe.fa`. The score cutoff is depended on the application, please select a prober cutoff value. And please ignore the Tm and delta G values.

**Comment by biozzq** [comment]
Hi @quwubin 

Yes, i will just run the commands you mentioned above. Can you take some time to explain for us that how scores can be related to the quality of the probes, the lower the better? Thank you very much.

Best wishes,
Zheng zhuqing

**Comment by quwubin** [comment]
In brief, the score is the basic alignment score, same as BLAST. 

I will find time to update the doc. 

Thanks.
