### ISSUE TITLE
I wonder how to get the source code of MFEprimer-3.0?

### ISSUE THREAD

**Issue by winni-liu** [quwubin/MFEprimer-3.0#7]
i want to learn the source code and want to study in the source code, but I cannot find the code in github and homepage

**Comment by quwubin** [comment]
Hi,

MFEprimer 2.0 is an open source version: https://github.com/quwubin/MFEprimer-2.0

Please check this version for the original thoughts of the algorithm.

Also, in [this paper](https://pubmed.ncbi.nlm.nih.gov/25697662/), I explained how to avoid non-amplicons in details.
