### ISSUE TITLE
Index size.

### ISSUE THREAD

**Issue by faustovrz** [quwubin/MFEprimer-3.0#8]
Hi,

I was trying to index a maize genome (2.5 GB) for checking specificity. However, mfeprimer filled up all the 70 GB of disk space in my laptop.  I estimate that for the 2.5GB genome I would need a 400 GB index. Should I expect the index to be this huge?

**Comment by quwubin** [comment]
<img width="752" alt="截屏2021-07-22 上午9 46 52" src="https://user-images.githubusercontent.com/9742/126580045-18bfa66b-0929-40c9-9f3f-b457452aa4c0.png">

Hi,

It will take 40 GB for the index file. It may take more GBs when indexing the genome.

**Comment by faustovrz** [comment]
Oh thank you.  The thing is I never got to see that .primerqc file. The index command made 35  files of 2G each before concatenating and finishing the task because it ran out of space. I'll try with a bigger external SSD.  It just seems odd that hast to go to 70 GB + of intermediate files.

**Comment by quwubin** [comment]
Yes, it will take more space if you have a bigger database.

Usually, we install MFEprimer in a Linux server, labtap is suitable for test and debug.

**Comment by faustovrz** [comment]
Thanks for the answer. Sorry for not making myself clear, but my question was rather if the index would be bigger if the genome is split into thousands of contigs rather than a few chromosomes for the same total assembly length. I'll follow your suggestion anyway.

**Comment by quwubin** [comment]
Almost no difference in size. In practice, I will split a large fasta file into parts and make each of them <= 3 GB.
