### ISSUE TITLE
mfeprimer3 run error

### ISSUE THREAD

**Issue by Niconlsam** [quwubin/MFEprimer-3.0#9]
When i run mfeprimer3, the program was exited with error as follow:

panic: runtime error: slice bounds out of range

goroutine 54770321 [running]:
github.com/quwubin/bio/mfeprimer.matchPair(0xc000026cc0, 0x10, 0xc0002b9040, 0xc00037e000, 0xc25d99a8f0, 0x1, 0x1, 0xc6b57256e8, 0x1, 0x1, ...)
        /ext-go/2/src/github.com/quwubin/bio/mfeprimer/mfeprimer.go:996 +0x143d
github.com/quwubin/bio/mfeprimer.searchPairedAmplicons.func2(0xc57799d980, 0xc000026cc0, 0x10, 0xc0002b9040, 0xc00037e000, 0xc0001dc630, 0xd770adf130, 0xc0799da040, 0xd8a4892d80, 0xc0249fdc80)
        /ext-go/2/src/github.com/quwubin/bio/mfeprimer/mfeprimer.go:678 +0x1e0
created by github.com/quwubin/bio/mfeprimer.searchPairedAmplicons
        /ext-go/2/src/github.com/quwubin/bio/mfeprimer/mfeprimer.go:676 +0x208
Command exited with non-zero status 2
7498.27user 2485.25system 5:49.28elapsed 2858%CPU (0avgtext+0avgdata 123345872maxresident)k
32481680inputs+8outputs (92405major+50524720minor)pagefaults 0swaps

The database i used was 8G and finally obtain the 171 G index file.How can i get the right way to deal with this problem?
Thank you so much.

**Comment by quwubin** [comment]
I couldn't get the exact reason, but please try to split the database into several small files, e.g., <= 3Gb for each one.
mfeprimer supports multiple databases selection "-d db1.fa -d db2.fa".
